### ISSUE TITLE
Implement extendedGCD via integer-gmp

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/arithmoi#114]
I tried to implement `Math.NumberTheory.GCD.extendedGCD` via `GHC.Integer.GMP.Internals.extendedGCDInteger` in [a temporary branch](https://github.com/Bodigrim/arithmoi/tree/remove-gcd).

```haskell
extendedGCD :: Integral a => a -> a -> (a, a, a)
extendedGCD a b = (fromInteger d', fromInteger u', fromInteger v')
  where
    (d', u', v') = extendedGCDInteger (toInteger a) (toInteger b)

extendedGCDInteger :: Integer -> Integer -> (Integer, Integer, Integer)
extendedGCDInteger a b = (d, u, v)
  where
    (# d, u #) = gcdExtInteger a b
    v = if b == 0 then 0 else (d - u * a) `quot` b
```

But after this change our test-suite fails with a horrible error:
```
Assertion failed: (0 <= gn && gn <= gn0), function integer_gmp_gcdext, 
file libraries/integer-gmp/cbits/wrappers.c, line 309.
```

I suspect the issue is with `integer-gmp` (did anyone ever used `integer_gmp_gcdext` at all?) and not with `arithmoi`, but currently I do not have time to investigate further and fill a proper trac ticket.

**Comment by Bodigrim** [comment]
Filed as https://ghc.haskell.org/trac/ghc/ticket/15350

**Comment by rockbmb** [comment]
Is this still relevant? I see that [15350](https://ghc.haskell.org/trac/ghc/ticket/15350) has been closed.

**Comment by Bodigrim** [comment]
Yes, it has been fixed in GHC 8.6.1. I still have to benchmark it and decide whether to use `Math.NumberTheory.GCD.extendedGCD` only for `Integer` or (if it is much faster even for small numbers) for other `Integral` types as well.

**Comment by rockbmb** [comment]
@Bodigrim what happened? I see here you committed d8f21ca, closed the issue, reverted d8f21ca and the reopened it. Is there a problem with `gcdExtInteger`?

**Comment by Bodigrim** [comment]
Yeah, unfortunately there is one more bug, discovered by more thorough QuickCheck testing. I reopened https://ghc.haskell.org/trac/ghc/ticket/15350

**Comment by Bodigrim** [comment]
Closing without resolution, since `gcdExt` was moved to `semirings` package and become out of scope of `arithmoi`. Anyways, it is a GHC bug.
