### ISSUE TITLE
Generate divisors in range

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/arithmoi#183]
Implement a function `divisorsInRange from to n`, which returns divisors of `n` between `from` and `to` (inclusively). The naive implementation would look this way:

```haskell
divisorsInRange :: (Ord a, UniqueFactorisation a) :: a -> a -> a -> [a]
divisorsInRange from to n = filter (\d -> from <= d && d <= to) (divisorsList n)
```

This becomes inefficient when `n` has tons of divisors out of `[from..to]` range. It would be desirable do not waste time and memory on generating divisors just to throw them away.

**Comment by jyoti246** [comment]
Can you please specify the range of `n`, `from` and `to`?

**Comment by Bodigrim** [comment]
`n` itself may be a huge integer, but such that its prime factorisation `factorise n` can be found quickly. Further, `0 <= from <= to <= n` and probably most of the time `from` is fairly small (like, `from = 0`) and `to` is much smaller than `n` (like `to ^ 2 < n`).

**Comment by jyoti246** [comment]
I have a working code for the above mentioned issue and need help in integrating it with the ecosystem and guidance for the same. So please tell me where I can merge my code and what are the changes required and I will do the necessary changes required to be done before making a pull request.
Below is my code:
```
import System.IO
import Data.Ratio
-- import Data.IORef (newIORef, readIORef, writeIORef)

mylog :: Integer -> Integer -> Integer
mylog a b 
	| ((a `mod` b) /= 0)  = 0
	| otherwise = (1 + mylog (a `div` b) b)


getfactors :: Integer -> Integer -> [(Integer,Integer)]
getfactors 1 _ = []
getfactors n st
		| lst == []  = [(n,1)]
		| otherwise	= (((head lst), (mylog n (head lst))):getfactors ( n `div` ((head lst) ^ (mylog n (head lst) ))) ((head lst)+1))
			where lst = (take 1 $ filter (\y -> (n `mod` y) == 0) [st .. (floor (sqrt (fromIntegral n)))])
				

precalc :: Integer -> [(Integer,Integer)] -> [Integer]
precalc n [] = []
precalc n (x:[]) = [n `div` (fst x ^ snd x )] 
precalc n (x:xs) = (n `div` (fst x ^ snd x )): (precalc (n `div` ((fst x) ^ (snd x) )) xs)


func :: Integer -> Integer -> [(Integer,Integer)] -> Int -> Integer -> Integer -> [Integer] -> [Integer]
func i temp fact ind a b arr 
	| (ind ==  (length fact)) = if (temp <= b && temp >= a) then [temp] else []
	| ( (i <= (snd (fact!!ind))) && temp > b) = []
	| ( (i <= (snd (fact!!ind))) && ((temp*(arr!!ind)) <= a)) = ((func (i+1) (temp * (fst (fact!!ind))) fact ind a b arr)  )
	| (i <= (snd (fact!!ind))) = ( (func 0 (temp) fact (ind+1) a b arr) ++ (func (i+1) (temp * (fst (fact!!ind))) fact ind a b arr)  ) 
	| otherwise = []

-- divisorsInRange :: (Ord a, UniqueFactorisation a) => a -> a -> a -> [a]
divisorsInRange :: Integer -> Integer -> Integer -> [Integer]
divisorsInRange from to n = func 0 1 (getfactors n 2) 0 from to (precalc n (getfactors n 2))
	
-- if sorted list required
quicksort :: [Integer] -> [Integer]
quicksort (x:xs) = lft ++ [x] ++ rgt
	where 
		lft = quicksort [a | a <- xs, a <= x]
		rgt = quicksort [a | a <- xs, a > x]
quicksort [] = []


main :: IO ()
main = do
    print (quicksort (func 0 1 (getfactors 48 2) 0 4 25 (precalc 48 (getfactors 48 2))))
```

**Comment by Bodigrim** [comment]
Thanks for your effort. Please make a PR to facilitate code review, adding this as a separate module, e. g., `Math.NumberTheory.Divisors`. 

Just some random remarks:

1. There is `Data.List.sort` in the standard library, no need for `quicksort`.
2. Please avoid `fst`, `snd`, `head` and resort to pattern matching.
3. Use `Math.NumberTheory.Primes.factorise` to obtain a prime factorisation instead of `getfactors`.
4. It is hard to understand what `func` is doing: neither its name nor type signature provide any clue.

**Comment by basimkhajwal** [comment]
I just realised that @jyoti246 had also been working on this, apologies for not checking the thread but it seems that our implementations work on different things so perhaps we can combine them.
