### ISSUE TITLE
Partial Factorization Algorithm

### ISSUE THREAD

**Issue by ensj** [Bodigrim/arithmoi#216]
Hello, I'm not sure if this is the right place to ask this, or if this is in the right format. Please let me know if I'm doing something wrong!   

I was trying to create a modified version of ECM using functions from this package, like `montgomeryFactorisation` in `Math.NumberTheory.Primes.Factorisation.Montgomery`. The compiler let me know that this was a hidden module though, and thus I couldn't use said functions I needed. Are there exposed functions in the package that I can use to create this feature?   
   
I just want the factorization to time out after a certain point and return the partial factorization that it came up with.

**Comment by Bodigrim** [comment]
Please use [`Math.NumberTheory.Primes.factorise`](http://hackage.haskell.org/package/arithmoi-0.11.0.1/docs/Math-NumberTheory-Primes.html#v:factorise). You can set timeout using a trick described at https://stackoverflow.com/a/11322162

**Comment by ensj** [comment]
Thank you very much!

**Comment by grandpascorpion** [comment]
I would be very interested in this feature
